In [ ]:
import numpy
print("Hello World")

def func(h):
  print(h)

func("Hello world")

Hello World


In [ ]:
%tensorflow_version 2.x
import tensorflow as tf

print(tf.version)

string = tf.Variable("This is string type tensor", tf.string)
number = tf.Variable(890, tf.int16)
floating = tf.Variable(3.14, tf.float64)

rank1_tensor = tf.Variable(["Elem1", "Elem2", "Elem2"], tf.string)
rank2_tensor = tf.Variable([["Elem1", "Elem2", "Elem2"], ["Elem1", "Elem2", "Elem2"]], tf.string)

tf.rank(rank2_tensor)
rank2_tensor.shape 

tensor1 = tf.ones([1,2,3])
tensor2 = tf.reshape(tensor1, [2,3,1])
tensor3 = tf.reshape(tensor1, [3,-1])
tensor4 = tf.zeros([1,2,3])

print(tensor1)
print(tensor2)
print(tensor3)

with tf.Session() as sess:
  tensor .eval()

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.7/dist-packages/tensorflow/_api/v2/version/__init__.py'>
tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


AttributeError: ignored